apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
    name: {{ include "app.fullname" . }}-dr
spec:
  host: {{ include "app.fullname" . }}
  subsets:
  - name: production
    labels:
      app: production
  - name: canary
    labels:
      app: canary
